# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e65668df707ab0f09bc4ef98c3277b1a9685084b556974c6cf8ba4418647fb9ae57411f9750153b64fc7894c17cd057390faae48e24d79e3ed01bf458692fa

test:
  secret_key_base: 1208de6b5e8a3b20887e07f5c296c3be5623b01cd0f710fe91dab3929edc8ca10e9d63cb4acb7da7e76b63cb4191a8fbeed51339fccf26abe9dc28195d9afa00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
